# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/codahale/blake2"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  name = "github.com/hanwen/go-fuse"
  revision = "95c6370914ac7822973d1893680e878e156f8d70"

[[constraint]]
  name = "github.com/op/go-logging"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/xxtea/xxtea-go"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "zombiezen.com/go/capnproto2"
  version = "2.17.1"

[prune]
  go-tests = true
  unused-packages = true
